# Generated by Django 5.2.3 on 2025-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorSuggestion",
            fields=[
                ("error_sig", models.TextField(primary_key=True, serialize=False)),
                ("culprit_pkg", models.CharField(max_length=60)),
                ("bad_version", models.CharField(max_length=40)),
                (
                    "good_version",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("confidence", models.FloatField()),
                ("docs_url", models.URLField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Beacon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("error", "error"), ("success", "success")],
                        max_length=7,
                    ),
                ),
                ("env_hash", models.CharField(max_length=12)),
                ("script_id", models.CharField(max_length=12)),
                ("error_sig", models.TextField(blank=True, null=True)),
                ("trace", models.TextField(blank=True, null=True)),
                ("ts", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["error_sig", "env_hash"],
                        name="telemetry_b_error_s_ad56c5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EnvSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("env_hash", models.CharField(max_length=12)),
                ("machine_arch", models.CharField(max_length=20)),
                ("packages", models.JSONField()),
                ("python_ver", models.CharField(max_length=20)),
                ("os_info", models.CharField(max_length=120)),
                ("env_vars", models.JSONField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("env_hash", "machine_arch")},
            },
        ),
    ]
