# Generated by Django 5.2.3 on 2025-06-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("total_errors_analyzed", models.IntegerField()),
                ("clusters_found", models.IntegerField()),
                ("patterns_found", models.IntegerField()),
                ("analysis_duration", models.FloatField()),
            ],
            options={
                "ordering": ["-analysis_date"],
            },
        ),
        migrations.CreateModel(
            name="ErrorCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_hash", models.CharField(max_length=64, unique=True)),
                ("error_signature", models.TextField()),
                ("error_count", models.IntegerField()),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("embedding", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cluster_hash"], name="analysis_er_cluster_d58e20_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConfigPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_key", models.CharField(max_length=100)),
                ("config_value", models.TextField()),
                ("occurrence_rate", models.FloatField()),
                ("global_rate", models.FloatField()),
                ("significance_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_patterns",
                        to="analysis.errorcluster",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cluster", "significance_score"],
                        name="analysis_co_cluster_1cf5a2_idx",
                    ),
                    models.Index(
                        fields=["config_key", "significance_score"],
                        name="analysis_co_config__cfe875_idx",
                    ),
                ],
                "unique_together": {("cluster", "config_key", "config_value")},
            },
        ),
    ]
